# Define el puerto en el que se ejecutará la aplicación, permitiendo que se configure a través de una variable de entorno (SERVER_PORT) o utilizando el valor predeterminado 8082 si no se proporciona.
server.port=${SERVER_PORT:8080}
# configuración de la conexión a la base de datos PostgreSQL
# jdbc -> Java Database Connectivity, es un API de Java para conectar con bases de datos
# 5433 -> Puerto donde se expone la BDD desde Docker.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/protecciones}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:9988776655}

# compara el modelo de datos con la base de datos, si no coinciden lanza un error
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
# Definde timezone para evitar problemas con fechas y horas, especialmente si la aplicación se ejecuta en un entorno con una zona horaria diferente a la de la base de datos.
spring.jpa.properties.hibernate.jdbc.time_zone=${TIMEZONE:America/Argentina/Buenos_Aires}

# Habilita el registro de las consultas SQL generadas por Hibernate, lo que es útil para depuración y optimización.
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# Activa Flyway para gestionar las migraciones de la base de datos, asegurando que el esquema de la base de datos esté actualizado con el modelo de datos definido en la aplicación.
# Entonces Spring arranca y se fija que hay una migración pendiente, entonces ejecuta el script de migración y luego arranca la aplicación normalmente.
spring.flyway.enabled=true
# Le dice a flyway dónde encontrar los scripts de migración, en este caso en la carpeta "db/migration" dentro del classpath de la aplicación. Esto es importante para que Flyway pueda aplicar las migraciones correctamente al iniciar la aplicación.
spring.flyway.locations=classpath:db/migration